name: fourcastnet-dev
channels:
  - conda-forge
dependencies:
  - python==3.8.12
  - pytorch==1.11.0
  - mpi4py
  - h5py
  - wandb
  - ruamel.yaml
  - tqdm
  - timm
  - einops
  - moviepy
  - imageio
  - matplotlib
  - netCDF4
  - pytest